"""datos del evento en la config

Revision ID: 7670faff6838
Revises: b5484a64fed6
Create Date: 2026-08-29 15:46:39.406842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7670faff6838"
down_revision: Union[str, None] = "b5484a64fed6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wishlist_config",
        sa.Column("evento_lugar", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "wishlist_config",
        sa.Column("evento_fecha", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "wishlist_config",
        sa.Column("evento_hora", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "wishlist_config",
        sa.Column("evento_texto", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wishlist_config", "evento_texto")
    op.drop_column("wishlist_config", "evento_hora")
    op.drop_column("wishlist_config", "evento_fecha")
    op.drop_column("wishlist_config", "evento_lugar")
    # ### end Alembic commands ###
