"""aviso arriba del formulario de rsvp

Revision ID: 80a44b49d94f
Revises: c1a2b3d4e5f6
Create Date: 2026-08-29 16:13:13.456159

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80a44b49d94f"
down_revision: Union[str, None] = "c1a2b3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wishlist_config",
        sa.Column("evento_aviso", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wishlist_config", "evento_aviso")
    # ### end Alembic commands ###
